/**
 * Client-side PDF and Excel export utilities.
 * PDF: Uses browser print dialog with styled HTML.
 * Excel: Generates CSV with proper formatting.
 */

interface ExportColumn {
  header: string;
  key: string;
  format?: "currency" | "number" | "date" | "text";
}

interface ExportOptions {
  title: string;
  subtitle?: string;
  columns: ExportColumn[];
  data: Record<string, any>[];
  filename: string;
  totals?: Record<string, number>;
}

const fmtCurrency = (n: number) =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", minimumFractionDigits: 2 }).format(n);

function formatValue(value: any, format?: string): string {
  if (value === null || value === undefined) return "—";
  if (format === "currency") return fmtCurrency(Number(value));
  if (format === "number") return Number(value).toLocaleString();
  return String(value);
}

export function exportToCSV(options: ExportOptions) {
  const { columns, data, filename, title } = options;
  const rows: string[] = [];

  // Header row
  rows.push(columns.map((c) => `"${c.header}"`).join(","));

  // Data rows
  data.forEach((row) => {
    rows.push(
      columns
        .map((c) => {
          const val = row[c.key];
          if (val === null || val === undefined) return '""';
          return `"${String(val).replace(/"/g, '""')}"`;
        })
        .join(",")
    );
  });

  // Totals row
  if (options.totals) {
    rows.push(
      columns
        .map((c, i) => {
          if (i === 0) return '"TOTAL"';
          if (options.totals![c.key] !== undefined) return `"${options.totals![c.key]}"`;
          return '""';
        })
        .join(",")
    );
  }

  const blob = new Blob([rows.join("\n")], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}.csv`;
  link.click();
  URL.revokeObjectURL(link.href);
}

export function exportToPDF(options: ExportOptions) {
  const { columns, data, title, subtitle, totals } = options;

  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  const html = `<!DOCTYPE html>
<html><head><title>${title}</title>
<style>
  body { font-family: 'Inter', -apple-system, sans-serif; margin: 40px; color: #1a1a2e; }
  h1 { font-size: 22px; margin: 0 0 4px; color: #0f172a; }
  .subtitle { font-size: 13px; color: #64748b; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { background: #0f172a; color: white; padding: 10px 12px; text-align: left; font-weight: 600; }
  td { padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
  tr:nth-child(even) { background: #f8fafc; }
  .text-right { text-align: right; }
  .total-row { font-weight: 700; background: #f1f5f9 !important; border-top: 2px solid #0f172a; }
  .footer { margin-top: 30px; font-size: 11px; color: #94a3b8; text-align: center; }
  @media print { body { margin: 20px; } }
</style></head><body>
<h1>${title}</h1>
${subtitle ? `<div class="subtitle">${subtitle}</div>` : ""}
<table>
  <thead><tr>${columns.map((c) => `<th class="${c.format === "currency" || c.format === "number" ? "text-right" : ""}">${c.header}</th>`).join("")}</tr></thead>
  <tbody>
    ${data
      .map(
        (row) =>
          `<tr>${columns
            .map(
              (c) =>
                `<td class="${c.format === "currency" || c.format === "number" ? "text-right" : ""}">${formatValue(row[c.key], c.format)}</td>`
            )
            .join("")}</tr>`
      )
      .join("")}
    ${
      totals
        ? `<tr class="total-row">${columns
            .map((c, i) => {
              if (i === 0) return `<td>TOTAL</td>`;
              if (totals[c.key] !== undefined) return `<td class="text-right">${formatValue(totals[c.key], c.format)}</td>`;
              return `<td></td>`;
            })
            .join("")}</tr>`
        : ""
    }
  </tbody>
</table>
<div class="footer">Generated by KukBook ERP — ${new Date().toLocaleDateString()}</div>
</body></html>`;

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => {
    printWindow.print();
  };
}

import { generateInvoicePDF, INVOICE_LAYOUTS } from './invoiceLayouts';

export function exportInvoicePDF(invoice: any, layoutKey: string = "professional", colors?: any) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  const html = generateInvoicePDF(invoice, layoutKey, colors);


  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => { printWindow.print(); };
}
