/**
 * Client-side PDF and Excel export utilities.
 * PDF: Uses browser print dialog with styled HTML.
 * Excel: Generates CSV with proper formatting.
 */

interface ExportColumn {
  header: string;
  key: string;
  format?: "currency" | "number" | "date" | "text";
}

interface ExportOptions {
  title: string;
  subtitle?: string;
  columns: ExportColumn[];
  data: Record<string, any>[];
  filename: string;
  totals?: Record<string, number>;
}

const fmtCurrency = (n: number) =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", minimumFractionDigits: 2 }).format(n);

function formatValue(value: any, format?: string): string {
  if (value === null || value === undefined) return "—";
  if (format === "currency") return fmtCurrency(Number(value));
  if (format === "number") return Number(value).toLocaleString();
  return String(value);
}

export function exportToCSV(options: ExportOptions) {
  const { columns, data, filename, title } = options;
  const rows: string[] = [];

  // Header row
  rows.push(columns.map((c) => `"${c.header}"`).join(","));

  // Data rows
  data.forEach((row) => {
    rows.push(
      columns
        .map((c) => {
          const val = row[c.key];
          if (val === null || val === undefined) return '""';
          return `"${String(val).replace(/"/g, '""')}"`;
        })
        .join(",")
    );
  });

  // Totals row
  if (options.totals) {
    rows.push(
      columns
        .map((c, i) => {
          if (i === 0) return '"TOTAL"';
          if (options.totals![c.key] !== undefined) return `"${options.totals![c.key]}"`;
          return '""';
        })
        .join(",")
    );
  }

  const blob = new Blob([rows.join("\n")], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}.csv`;
  link.click();
  URL.revokeObjectURL(link.href);
}

export function exportToPDF(options: ExportOptions) {
  const { columns, data, title, subtitle, totals } = options;

  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  const html = `<!DOCTYPE html>
<html><head><title>${title}</title>
<style>
  body { font-family: 'Inter', -apple-system, sans-serif; margin: 40px; color: #1a1a2e; }
  h1 { font-size: 22px; margin: 0 0 4px; color: #0f172a; }
  .subtitle { font-size: 13px; color: #64748b; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { background: #0f172a; color: white; padding: 10px 12px; text-align: left; font-weight: 600; }
  td { padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
  tr:nth-child(even) { background: #f8fafc; }
  .text-right { text-align: right; }
  .total-row { font-weight: 700; background: #f1f5f9 !important; border-top: 2px solid #0f172a; }
  .footer { margin-top: 30px; font-size: 11px; color: #94a3b8; text-align: center; }
  @media print { body { margin: 20px; } }
</style></head><body>
<h1>${title}</h1>
${subtitle ? `<div class="subtitle">${subtitle}</div>` : ""}
<table>
  <thead><tr>${columns.map((c) => `<th class="${c.format === "currency" || c.format === "number" ? "text-right" : ""}">${c.header}</th>`).join("")}</tr></thead>
  <tbody>
    ${data
      .map(
        (row) =>
          `<tr>${columns
            .map(
              (c) =>
                `<td class="${c.format === "currency" || c.format === "number" ? "text-right" : ""}">${formatValue(row[c.key], c.format)}</td>`
            )
            .join("")}</tr>`
      )
      .join("")}
    ${
      totals
        ? `<tr class="total-row">${columns
            .map((c, i) => {
              if (i === 0) return `<td>TOTAL</td>`;
              if (totals[c.key] !== undefined) return `<td class="text-right">${formatValue(totals[c.key], c.format)}</td>`;
              return `<td></td>`;
            })
            .join("")}</tr>`
        : ""
    }
  </tbody>
</table>
<div class="footer">Generated by KukBook ERP — ${new Date().toLocaleDateString()}</div>
</body></html>`;

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => {
    printWindow.print();
  };
}

export function exportInvoicePDF(invoice: any) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  const items = invoice.items || [];
  const html = `<!DOCTYPE html>
<html><head><title>Invoice ${invoice.invoiceId}</title>
<style>
  body { font-family: 'Inter', -apple-system, sans-serif; margin: 40px; color: #1a1a2e; }
  .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
  .company { font-size: 24px; font-weight: 700; color: #0f172a; }
  .invoice-title { font-size: 28px; font-weight: 700; color: #0f172a; text-align: right; }
  .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
  .meta-box { padding: 15px; background: #f8fafc; border-radius: 8px; }
  .meta-label { font-size: 11px; color: #64748b; text-transform: uppercase; font-weight: 600; }
  .meta-value { font-size: 14px; margin-top: 4px; font-weight: 500; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  th { background: #0f172a; color: white; padding: 10px 12px; text-align: left; font-size: 12px; }
  td { padding: 10px 12px; border-bottom: 1px solid #e2e8f0; font-size: 13px; }
  .text-right { text-align: right; }
  .total-section { text-align: right; margin-top: 10px; }
  .total-line { display: flex; justify-content: flex-end; gap: 40px; padding: 6px 0; font-size: 14px; }
  .grand-total { font-size: 18px; font-weight: 700; border-top: 2px solid #0f172a; padding-top: 10px; }
  .status { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }
  .status-Paid { background: #dcfce7; color: #166534; }
  .status-Sent { background: #dbeafe; color: #1e40af; }
  .status-Draft { background: #f3f4f6; color: #374151; }
  .status-Overdue { background: #fee2e2; color: #991b1b; }
  .footer { margin-top: 40px; font-size: 11px; color: #94a3b8; text-align: center; }
  @media print { body { margin: 20px; } }
</style></head><body>
<div class="header">
  <div><div class="company">KukBook</div><div style="color:#64748b;font-size:13px">Accounting ERP</div></div>
  <div><div class="invoice-title">INVOICE</div><div style="text-align:right;color:#64748b;font-size:14px">${invoice.invoiceId}</div></div>
</div>
<div class="meta">
  <div class="meta-box"><div class="meta-label">Bill To</div><div class="meta-value">${invoice.customerName}</div></div>
  <div class="meta-box">
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">
      <div><div class="meta-label">Date</div><div class="meta-value">${invoice.date || "—"}</div></div>
      <div><div class="meta-label">Due Date</div><div class="meta-value">${invoice.dueDate || "—"}</div></div>
      <div><div class="meta-label">Status</div><div class="meta-value"><span class="status status-${invoice.status}">${invoice.status}</span></div></div>
    </div>
  </div>
</div>
<table>
  <thead><tr><th>Description</th><th class="text-right">Qty</th><th class="text-right">Rate</th><th class="text-right">Amount</th></tr></thead>
  <tbody>
    ${items.length > 0 ? items.map((item: any) => `<tr><td>${item.description || "—"}</td><td class="text-right">${item.qty}</td><td class="text-right">₹${Number(item.rate).toFixed(2)}</td><td class="text-right">₹${(Number(item.qty) * Number(item.rate)).toFixed(2)}</td></tr>`).join("") : `<tr><td colspan="4" style="text-align:center;color:#94a3b8">No line items</td></tr>`}
  </tbody>
</table>
<div class="total-section">
  <div class="total-line"><span>Subtotal:</span><span>₹${Number(invoice.total).toFixed(2)}</span></div>
  <div class="total-line grand-total"><span>Total:</span><span>₹${Number(invoice.total).toFixed(2)}</span></div>
</div>
<div class="footer">Generated by KukBook ERP — ${new Date().toLocaleDateString()}</div>
</body></html>`;

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => { printWindow.print(); };
}
